// <auto-generated />
using Heating_Optimization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeatingOptimization.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250506112950_TeamCredentials")]
    partial class TeamCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Heating_Optimization.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Martin",
                            Password = "password1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cristiann",
                            Password = "password2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tony",
                            Password = "password3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Victor",
                            Password = "password4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marc",
                            Password = "password5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kristian",
                            Password = "password5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
